# Generated by Django 3.2.10 on 2024-03-08 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('director', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('average_audience', models.IntegerField(null=True)),
                ('audience_showcnt', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movie_all',
            fields=[
                ('movie_code', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(null=True)),
                ('rank_intensity', models.IntegerField(null=True)),
                ('korean_name', models.CharField(max_length=255, null=True)),
                ('open_date', models.CharField(max_length=255, null=True)),
                ('audiacc', models.CharField(max_length=255, null=True)),
                ('audicnt_showcnt', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=100)),
                ('running_time', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djan.choice')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djan.movie_all')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='movie_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djan.choice')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djan.movie_all')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='movie_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(null=True)),
                ('accessible', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('poster', models.URLField(null=True)),
                ('movie', models.ManyToManyField(related_name='movie_all', to='djan.movie_all')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djan.movie_all'),
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djan.movie_all')),
            ],
        ),
    ]
