# Generated by Django 3.2.10 on 2024-03-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan', '0002_auto_20240309_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='music_director',
            fields=[
                ('peoplenm', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('work_count', models.IntegerField(null=True)),
                ('average_audiacc', models.IntegerField(null=True)),
                ('audience_showcnt', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trusted_actor',
            fields=[
                ('actor', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('number', models.IntegerField(null=True)),
                ('avg_audience', models.IntegerField(null=True)),
                ('audience_showcnt', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trusted_director',
            name='audience_showcnt',
            field=models.FloatField(null=True),
        ),
    ]
