# Generated by Django 3.2.10 on 2024-03-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan', '0004_auto_20240309_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trusted_actor',
            name='average_audience',
        ),
        migrations.AddField(
            model_name='trusted_actor',
            name='avg_audience',
            field=models.IntegerField(null=True),
        ),
    ]
