# Generated by Django 3.2.10 on 2024-03-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djan', '0005_auto_20240309_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_worker',
            fields=[
                ('id', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('naver_review', models.TextField(null=True)),
                ('same_comment', models.IntegerField(null=True)),
                ('review_score', models.IntegerField(null=True)),
            ],
        ),
    ]
